export const projectList = [
  {
    _id: "668b8681e34e9da6153e2d33",
    title: "Gurukul.com",
    desc: "A MERN based E-Learning web-app offering video courses, research papers, and downloadable hand notes.",
    github: "https://github.com/rohitsinghkcodes/gurukul.com",
    display: 1,
    createdAt: "2024-07-08T06:26:09.830Z",
    updatedAt: "2024-07-08T06:26:09.830Z",
    __v: 0,
    img: "https://raw.githubusercontent.com/rohitsinghkcodes/RESOURCES/master/Images/portfolio-rohitkcodes/gurukul.jpg",
  },
  {
    _id: "668b86c4e34e9da6153e2d35",
    title: "TechMart",
    desc: "A MERN based premium e-commerce web-app for buying best computer hardwares, gaming accessories, and IT essentials.",
    github: "https://github.com/rohitsinghkcodes/TechMart",
    display: 2,
    createdAt: "2024-07-08T06:27:16.133Z",
    updatedAt: "2024-07-08T06:27:16.133Z",
    __v: 0,
    img: "https://raw.githubusercontent.com/rohitsinghkcodes/RESOURCES/master/Images/portfolio-rohitkcodes/techmart.jpg",
  },
  {
    _id: "668b8755e34e9da6153e2d37",
    title: "SOV",
    desc: "Socializing On Vocals is an audio-centric app for enjoying songs, poetry, jingles, and audio blogs in short format content.",
    github: "https://github.com/rohitsinghkcodes/Socializing-On-Vocals",
    display: 3,
    createdAt: "2024-07-08T06:29:41.612Z",
    updatedAt: "2024-07-08T06:29:41.612Z",
    __v: 0,
    img: "https://raw.githubusercontent.com/rohitsinghkcodes/RESOURCES/master/Images/portfolio-rohitkcodes/sov.png",
    web_link: "https://socializing-on-vocals-download.netlify.app/",
  },
  {
    _id: "668b99dc4aaec8d35828cb7c",
    title: "Samachar",
    desc: "A Flutter app that provides users with the latest news headlines from a variety of news sources in a categorical fashion.",
    github: "https://github.com/rohitsinghkcodes/samachar",
    img: "https://raw.githubusercontent.com/rohitsinghkcodes/RESOURCES/master/Images/portfolio-rohitkcodes/samachar.jpg",
    display: 4,
    createdAt: "2024-07-08T07:48:44.908Z",
    updatedAt: "2024-07-08T07:48:44.908Z",
    __v: 0,
    web_link: "https://samacharapk.netlify.app/",
  },
  {
    _id: "668b87e6e34e9da6153e2d3b",
    title: "Letsnote",
    desc: "Letsnote is a feature-rich note-taking web application powered by FastAPI, integrating robust task management functionalities.",
    github: "https://github.com/rohitsinghkcodes/FastAPI-Notes-App",
    display: 5,
    createdAt: "2024-07-08T06:32:06.885Z",
    updatedAt: "2024-07-08T06:32:06.885Z",
    __v: 0,
    img: "https://raw.githubusercontent.com/rohitsinghkcodes/RESOURCES/master/Images/portfolio-rohitkcodes/note1.jpg",
  },
  {
    _id: "668b8797e34e9da6153e2d39",
    title: "Anonymask",
    desc: "Anonymask is a robust Flutter application that utilizes OpenAI's API for engaging in anonymous, interactive conversations.",
    github: "https://github.com/rohitsinghkcodes/Socializing-On-Vocals",
    display: 6,
    createdAt: "2024-07-08T06:30:47.154Z",
    updatedAt: "2024-07-08T06:30:47.154Z",
    __v: 0,
    img: "https://raw.githubusercontent.com/rohitsinghkcodes/RESOURCES/master/Images/portfolio-rohitkcodes/anonymask.png",
  },
];
